# Generated by Django 5.0.4 on 2024-04-26 15:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='images',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\joaop\\PycharmProjects\\flavornetwork\\flavornetwork\\media\\recipes'), upload_to='images/%Y/%m/%d/'),
        ),
    ]
