# Generated by Django 5.0.4 on 2024-04-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_recipe_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='users/images/default.png', upload_to='users/images/'),
        ),
    ]
