# Generated by Django 5.0.4 on 2024-04-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='users/images/default.png', upload_to='users/images/'),
        ),
    ]
