# Generated by Django 4.2.11 on 2024-05-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_recipe_calories_recipe_carbs_recipe_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenges/images/'),
        ),
    ]
